In [27]:
import os
import pandas as pd
import numpy as np
from sklearn import svm

In [28]:
cd Desktop/

[WinError 2] 系统找不到指定的文件。: 'Desktop/'
C:\Users\86137\Desktop


In [4]:
feature = pd.read_csv('feature.csv',header=-1)
label = pd.read_csv('label.csv',header=-1)

In [5]:
feature.head()

0     1     2    3     4     5     6     7     8     9   ...    30   31  \
0  0.00  0.66  0.09  0.0  0.97  0.19  0.37  0.14  0.35  0.00  ...  0.00  1.0   
1  0.84  0.53  0.82  0.0  0.97  0.19  0.64  0.14  0.98  0.33  ...  0.00  1.0   
2  0.10  0.79  0.42  0.0  0.97  0.19  0.58  0.14  0.22  0.00  ...  0.00  1.0   
3  0.81  0.65  0.99  0.0  0.97  0.19  0.69  0.14  0.52  0.00  ...  0.01  1.0   
4  0.10  0.79  0.42  0.0  0.97  0.19  0.63  0.14  0.91  0.00  ...  0.00  1.0   

     32    33    34   35    36    37    38    39  
0  0.38  0.73  0.67  0.0  0.59  0.14  0.29  0.73  
1  0.38  0.65  0.67  0.0  0.59  0.10  0.29  0.67  
2  1.00  0.65  0.29  0.0  0.24  0.10  0.11  0.67  
3  1.00  0.65  0.29  0.0  0.24  0.03  0.11  0.67  
4  1.00  0.65  0.29  0.0  0.24  0.10  0.11  0.67  

[5 rows x 40 columns]

In [6]:
label.head()

0
0  1
1  0
2  0
3  0
4  0

In [8]:
x = feature.values
y = label.values.reshape(-1,)

In [58]:
# svm
clf = svm.SVC(gamma='scale',class_weight='balanced')
clf.fit(x,y)
predict_y = clf.predict(x)

print (predict_y)

[1 0 0 ... 0 1 1]


In [59]:
print (len((np.argwhere(predict_y!=y))))

23253


In [61]:
# decision tree
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf.fit(x,y)
predict_y = clf.predict(x)
print (len((np.argwhere(predict_y!=y))))

863


In [62]:
print (predict_y)

[1 0 0 ... 0 0 0]


In [13]:
# 保存模型
import pickle
with open('tree.pickle','wb') as fw:
    pickle.dump(clf,fw)
    
# 加载模型
# with open('tree.pickle','rb') as fr:
#     clf = pickle.load(fr)

In [20]:
# 加载测试集
test = pd.read_csv('test.csv')
test.head()

ID                 date                   A1                   A2  \
0   1  1900-07-01 23:30:00  6639933182047261336  -266997934034473966   
1   4  1900-07-01 23:30:00 -7834936860748470404  7969469182960222711   
2   6  1900-07-01 23:30:00  4650039790794677128  2774817855788439768   
3   8  1900-07-01 23:30:00  6639933182047261336  -266997934034473966   
4  10  1900-07-01 23:30:00  4650039790794677128  2774817855788439768   

                    A3                   B1                   B2  \
0  8246390433496480203  9054247727413374425 -7341558312017818025   
1  2581139938865571426 -8639208079192601888  8626319289109649330   
2  9040931202870639290 -8639208079192601888  8626319289109649330   
3  8246390433496480203 -2574610792515121895 -4277426050680369930   
4  9040931202870639290 -8639208079192601888  8626319289109649330   

                    B3                   C1                   C2  ...  E20  \
0 -8283098956013433384 -7138755224678627378 -6705654019294684257  ...    0   
1 -5533056078568352733 -1111151172125569605 -6705654019294684257  ...    0   
2 -5533056078568352733  4001157654716108171 -6705654019294684257  ...    0   
3  3840025076341162581 -1800439894211020962 -6705654019294684257  ...    0   
4 -5533056078568352733 -6903606117160868970 -6705654019294684257  ...    0   

        E21       E22  E23  E24  E25  E26  E27  E28  E29  
0  0.266158  0.619259   17    6    0    4    6    4   20  
1  0.266158 -1.600320   17   14    0   10    2   10   20  
2  0.266158  0.619259   17    6    0    4    2    4   20  
3  0.266158  0.619259   19    6    0    4    0    4   22  
4  0.266158  0.619259   17    6    0    4    2    4   20  

[5 rows x 42 columns]

In [21]:
# 去除前两列特征
test.drop(columns=['ID','date'],inplace=True)
test.head()

A1                   A2                   A3  \
0  6639933182047261336  -266997934034473966  8246390433496480203   
1 -7834936860748470404  7969469182960222711  2581139938865571426   
2  4650039790794677128  2774817855788439768  9040931202870639290   
3  6639933182047261336  -266997934034473966  8246390433496480203   
4  4650039790794677128  2774817855788439768  9040931202870639290   

                    B1                   B2                   B3  \
0  9054247727413374425 -7341558312017818025 -8283098956013433384   
1 -8639208079192601888  8626319289109649330 -5533056078568352733   
2 -8639208079192601888  8626319289109649330 -5533056078568352733   
3 -2574610792515121895 -4277426050680369930  3840025076341162581   
4 -8639208079192601888  8626319289109649330 -5533056078568352733   

                    C1                   C2                   C3  D1  ...  \
0 -7138755224678627378 -6705654019294684257 -6915019868152657482   1  ...   
1 -1111151172125569605 -6705654019294684257 -4108156365925589797   1  ...   
2  4001157654716108171 -6705654019294684257 -4818755172019786308   0  ...   
3 -1800439894211020962 -6705654019294684257 -6369330351977459030   0  ...   
4 -6903606117160868970 -6705654019294684257  8690280099524284095   0  ...   

   E20       E21       E22  E23  E24  E25  E26  E27  E28  E29  
0    0  0.266158  0.619259   17    6    0    4    6    4   20  
1    0  0.266158 -1.600320   17   14    0   10    2   10   20  
2    0  0.266158  0.619259   17    6    0    4    2    4   20  
3    0  0.266158  0.619259   19    6    0    4    0    4   22  
4    0  0.266158  0.619259   17    6    0    4    2    4   20  

[5 rows x 40 columns]

In [22]:
# 数据归一化
from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()
test = min_max_scaler.fit_transform(test)

AttributeError: 'numpy.ndarray' object has no attribute 'head'

In [23]:
print (test)

[[0.93732508 0.48489712 0.94909568 ... 0.10169492 0.08823529 0.65517241]
 [0.         0.93206257 0.640688   ... 0.03389831 0.26470588 0.65517241]
 [0.80846887 0.65004012 0.99234928 ... 0.03389831 0.08823529 0.65517241]
 ...
 [0.80846887 0.65004012 0.99234928 ... 0.18644068 0.08823529 0.65517241]
 [0.93732508 0.48489712 0.94909568 ... 0.         0.08823529 0.75862069]
 [0.93732508 0.48489712 0.94909568 ... 0.         0.08823529 0.72413793]]


In [39]:
# 用模型进行预测
test_label = clf.predict_proba(test)
print (test_label)

[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [0. 1.]
 [1. 0.]
 [0. 1.]]


In [52]:
print (x)
print (y)

[[0.   0.66 0.09 ... 0.14 0.29 0.73]
 [0.84 0.53 0.82 ... 0.1  0.29 0.67]
 [0.1  0.79 0.42 ... 0.1  0.11 0.67]
 ...
 [0.94 0.48 0.95 ... 0.02 0.11 0.67]
 [0.   0.63 0.87 ... 0.   0.29 0.77]
 [0.81 0.65 0.99 ... 0.02 0.11 0.67]]
[1 0 0 ... 0 0 0]


In [55]:
# xboost

from xgboost import XGBClassifier
model = XGBClassifier()
model.fit(x,y)
predict_y = model.predict(x)
print (predict_y)
# print (len((np.argwhere(predict_y!=y))))

[0 0 0 ... 0 0 0]


In [56]:
print (len((np.argwhere(predict_y!=y))))

10075


In [37]:
print (len((np.argwhere(predict_y==1))))
print (len((np.argwhere(y==1))))

671
10244


In [35]:
print (x)
print (y)

[[0.   0.66 0.09 ... 0.14 0.29 0.73]
 [0.84 0.53 0.82 ... 0.1  0.29 0.67]
 [0.1  0.79 0.42 ... 0.1  0.11 0.67]
 ...
 [0.94 0.48 0.95 ... 0.02 0.11 0.67]
 [0.   0.63 0.87 ... 0.   0.29 0.77]
 [0.81 0.65 0.99 ... 0.02 0.11 0.67]]
[1 0 0 ... 0 0 0]


In [54]:
# MLP
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier()
clf.fit(x,y)
predict_y = clf.predict(x)
print (predict_y)

D:\anaconda\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[0 0 0 ... 0 0 0]


In [42]:
print (len((np.argwhere(predict_y!=y))))

10011


In [57]:
test_label = clf.predict_proba(test)
print (test_label)

[[0.74759028 0.25240972]
 [0.93830923 0.06169077]
 [0.78222275 0.21777725]
 ...
 [0.75012089 0.24987911]
 [0.81476157 0.18523843]
 [0.67855798 0.32144202]]
